/**
 * Hand-managed type declarations for the patient app.
 * `expo-env.d.ts` is auto-regenerated by expo-cli on every start, so any
 * declarations we add there get erased. This file is stable.
 */

/// <reference types="expo-router/types" />

declare namespace NodeJS {
  interface ProcessEnv {
    EXPO_PUBLIC_SUPABASE_URL?: string;
    EXPO_PUBLIC_SUPABASE_ANON_KEY?: string;
    EXPO_PUBLIC_GOOGLE_MAPS_API_KEY_ANDROID?: string;
    EXPO_PUBLIC_GOOGLE_MAPS_API_KEY_IOS?: string;
    // Role launcher → sibling app URLs (see app/index.tsx). Optional; falls
    // back to local dev ports when unset.
    EXPO_PUBLIC_DRIVER_URL?: string;
    EXPO_PUBLIC_OPERATOR_URL?: string;
    EXPO_PUBLIC_HOSPITAL_URL?: string;
  }
}

declare const process: {
  env: NodeJS.ProcessEnv;
};
